spring:
  profiles:
    include: prod
  application:
    name: security-oauth2-rbac

mybatis:
  # 实体类扫描路径
  type-aliases-package: com.james.example.cloud.oauth.domain
  # xml 扫描路径
  mapper-locations: classpath:mapper/*.xml