server:
  port: 8084

spring:
  application:
    name: spring-boot-admin-nacos-client
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: localhost:8848
# TODO 若使用注册中心，则不需要引入 spring-boot-admin-client 并配置相关参数
#  boot:
#    admin:
#      client:
#        url: http://localhost:8086
#
# 使用注册中心后需依赖 spring-boot-starter-actuator 并配置如下
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always