server:
  port: 10015


# Nacos EndPoint: http://ip:port/actuator/nacos-discovery
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

