server:
  port: 8841

spring:
  #  profiles:
  # 配置环境
  #    active: dev
  #    active: prod
  application:
    # Dubbo 应用名称
    name: spring-cloud-nacos-dubbo-client
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        enabled: true
        register-enabled: true
        server-addr: 114.67.106.207:8848

dubbo:
  cloud:
    # 用于服务消费方订阅服务提供方的应用名称的列表
    # 若需订阅多应用，使用 "," 分割。 不推荐使用默认值为 "*"，它将订阅所有应用。
    subscribed-services: spring-cloud-nacos-dubbo-server
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://114.67.106.207
