server:
  port: 8084

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:   # 路由数组 [路由 就是指定当请求满足什么条件的时候转到哪个微服务]
        - id: hello_route  # 当前路由的标识，要求唯一
          uri: http://localhost:8083/hello  # 请求要转发到的地址
          order: 1    # 路由的优先级，数字越小级别越高
          predicates:   # 断言（就是路由转发要满足的条件）
            - Path=/hello  # 当强求路径满足 Path 指定的规则时，才会进行路由转发
#          filters:  # 过滤器。请求在传递过程中可以用过过滤器对其进行一定的修改
#            - StripPrefix=1 # 转发之前去掉 1 层路径
