server:
  port: 8840

spring:
  application:
    name: micro-service-redis-cache
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33061/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: james
    password: james2020+
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MasterHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 114.67.106.207
    port: 6379
    password: james2020+
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 2000ms
  cache:
    type: redis

mybatis:
  # 实体类扫描路径
  type-aliases-package: com.james.example.micro.service.redis.domain
  # xml 扫描路径
  mapper-locations: classpath:mapper/*.xml