server:
  port: 10020

spring:
  boot:
    admin:
      notify:
        mail:
          to: ${mail.to}
          from: ${mail.username}
          ignore-changes: ""
  security:
    user:
      name: james
      password: James2020+
  mail:
    host: smtp.qq.com
    protocol: smtp
    username: ${mail.username}
    password: ${mail.password}
    default-encoding: UTF-8
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.smtp.display.sendmail: ${mail.username}
    properties.mail.smtp.display.sendname: Admin
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
