server:
  port: 8050
spring:
  rabbitmq:
    addresses: 114.67.106.207:5673
    username: guest
    password: james2020+
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        # 手动应答模式
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10

