server:
  port: 8050
spring:
  rabbitmq:
    addresses: 47.98.112.234:5673
    username: admin
    password: Law@2018
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        # 手动应答模式
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10

