server:
  port: 8840

# Dubbo nacos 配置
dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.james.example.cloud.nacos.dubbo.server.impl
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://114.67.106.207

spring:
  application:
    name: spring-cloud-nacos-dubbo-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 114.67.106.207:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.67.106.207:33067/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: james
    password: james2020+
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MasterHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 114.67.106.207
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 2000ms
  cache:
    type: redis

mybatis:
  # 实体类扫描路径
  type-aliases-package: com.james.example.cloud.nacos.dubbo.dao.domain
  # xml 扫描路径
  mapper-locations: classpath:mapper/*.xml