spring:
  profiles:
    active: prod
  application:
    name: security-oauth2-rbac
  main:
    allow-bean-definition-overriding: true

mybatis:
  # 实体类扫描路径
  type-aliases-package: com.james.example.cloud.oauth.domain
  # xml 扫描路径
  mapper-locations: classpath:mapper/*.xml